apiVersion: v2
name: socle-observability
description: A Helm chart for Kubernetes to deploy GrafanaDashboard and PrometheusRule for the socle's services
type: application
version: 1.0.0
dependencies:
- name: dso-observability
  alias: observability
  version: ">=0.0.0 <1.0.0"
  repository: https://cloud-pi-native.github.io/helm-charts
maintainers:
  - name: cloud-pi-native
    email: cloudpinative-relations@interieur.gouv.fr
    url: https://cloud-pi-native.fr
