# -- Informations communes, notamment appliquées en label sur les différents objets
common:
  dso/project: project
  dso/environment: env
application:
  destination:
    # -- Nom du namespace applicatif cible
    namespace: app1
  quota:
    # -- (int) Quota CPU pour le namespace
    cpu:
    # -- (int) Quota GPU pour le namespace
    gpu:
    # -- Quota mémoire pour le namespace
    memory:
  vault:
    # -- URL du Vault à utiliser par Vault Secret Operator
    url:
    # -- Nom du Key Value store dans Vault
    kvName: forge-dso
    # -- ID du rôle à utiliser (méthode AppRole)
    roleId:
    # -- Secret de connexion avec ce rôle
    secretId:
    # -- Répertoire racine des projets à utiliser dans Vault
    projectsRootDir: forge-mi/projects
