apiVersion: v2
name: dso-grafana
description: This Helm chart deploy Grafana instances and default dashboards for each projects read from values file.
type: application
version: 1.6.0
dependencies:
- name: grafana-operator
  repository: oci://ghcr.io/grafana/helm-charts
  version: v5.10.0
maintainers:
  - name: cloud-pi-native
    email: cloudpinative-relations@interieur.gouv.fr
    url: https://cloud-pi-native.fr
